const categories = {
  HotCold: [
    "COFFEE",
    "TEA",
    "COFFEE Bar",
    "Soft Drinks (Pepsi, Sprite, Fanta)",
    "Cold Drinks Can",
    "Shake (Cold Coffee, Strawberry, Pista Butter Scotch)",
    "Mocktail Bar (Virgin Mohito, Blue Caraco, Passion Fruit)",
    "Coctail Bar",
    "Fresh Juice",
    "Tomato Soup",
    "Manchow Soup",
    "Sweet Corn Soup",
    "Sweey & Sour Soup",
    "Mushroom Soup",
    "Almond Soup",
    "Chicken Soup",
    "Mutton Soup",
    "Water Bottle + Camper",
    "Water Bottle",
    "Water Camper"
    
  ],
    Breakfast: [
    "Paneer Pakoda",
    "Veg Cutlets",
    "Mix Pakoda",
    "Gobi Pakoda",
    "Pineapple Pakoda",
    "Kaju Kofta",
    "Palak Tikki",
    "Palak Patta Pakoda",
    "Aloo Samosa",
    "Coctail Samosa",
    "Cholle Bhature",
    "Cholle Puri",
    "Aloo Puri",
    "Cold Sandwich",
    "Grilled Sandwich",
    "Poha",
    "Aloo Paratha",
    "Veg Chilla",
    "Moonglet",
    "Idly Sambhar",
    "Khaman Dhokla",
    "Jullee",
    "Pastry",
    "Gulab Jamun",
    "Barfi",
    "Badaam Sandwich",
    "Kaju Katli",
    "NON VEG",
    // NON VEG
    "Omelette",
    "Chicken 65",
    "Fish Pakoda",
    "Lemon Chicken",
    "Egg Curry",  
    "Butter Pouch",
    "Pot Kaleji",
    "Fish Finger",
    "Lemon Butter Fish",
    

    ],
  Stalls: [
    "Lacha Tikki",
    "Aaloo Tikki",
    "Raj Bhog Bhalle",
    "Dahi Bhalle",
    "Kanjhi Bhalla",
    "Raj Kachori",
    "Palak Patta Chaat",
    "Gol Gappe",
    "Pav Bhaji",
    "Dosa",
    "SweetCorn",
    "Paneer Chilla",
    "Sambhar Vada",
    "Amritsari Naan Cholle",
    "Matar Kulcha",
    "Veg Chowmin",
    "Ice Gola",
    "Popcorn",
    "Russian Chaat",
    "English Chaat",
    "Garam Chaat",
    "Sugar Candy",
    "Fresh Fruit",
  ],
  Starters: [
    "French Fries",
    "Paneer Finger",
    "KFC Paneer",
    "Cheese Ball",
    "KFC Chaap",
    "Spring Roll",
    "Mushroom Duplex",
    "Hara Bhara Kebab",
    "Cocktail Kebab",
    "Italian Roll",
    "Veg Lolipop",
    "Fruit Kebab",
    "Cheese Stick",
    "Cheese Corn Roll",
    "Dahi Ke Cholle",
    "LIVE",
    "Manchurian",
    "Honey Chilli Paneer",
    "Honey Chilli Cauliflower",
    "Honey Chilli Potato",
    "Hakka Noodles",
    "Pasta (Red+White)",
    "Pepper Sweet Corn",
    "Paneer Kaleji",
    "Bruschetta",
    "Cheese Nachos",
    "Steam Dimsum",
    "Italian Wrap",
    "Kathi Roll",
    "Cucumber Shot",
    "Tacos",
    "Maggie",
    "Canopy",
    "Dragon Paneer Chilli",
    "Paneer Tikka",
    "Achari Soyabean Tikka",
    "Malai Soyabean Tikka",
    "Masala Soyabean Tikka",
    "Hariyali Paneer Tikka",
    "Pizza",
    "NON VEG",
    // NON VEG
    "Chicken Tikka",
    "Chicken Tandoori",
    "Fish Tandoori",
    "Chicken Tangri",
    "Stuffed Tangri Kebab",
    "Dragon Chilli",
    "Chicken 65",
    "Tawa Mutton",
    "Handi Chicken",
    "Chicken Chili (Boneless)",
    "Pomfret Fish",
    "Tawa Red Sniper",
    "Lemon Fish",
    "Fish Pakoda",
    "Tawa Chicken",
    "Afghani Chicken",
    "Murg Achaari Tikka", 
    "Murg Amritsari Tikka",
    "Murg Galati Kebab",
    "Murg Malai Seek Kabab",
    "Mutton Malai Seek Kabab",
    "Chicken Lollipop",
    "Mutton Tandoori",
    "Murg kalmi Kabab",
    "Chicken Golden Fry",
    "Murg Reshmi Pakora",
    "Fish Pakora",
    "Bear Butter Fish Finger",
    "Lahsun Fish Finger",
  

  ],
  Sweets: [
    "Moong Dal Halwa",
    "GondPak",
    "Gajar Halwa",
    "Sweet Corn Halwa",
    "Pineapple Halwa",
    "Gourd Halwa(Kadu)",
    "Mirch Halwa",
    "Beetroot Halwa",
    "Badam Halwa",
    "Walnut Halwa(Akhrot)",
    "Shahi Halwa",
    "Jalebi Rabdi",
    "Faluda Rabdi",
    "Indrani",
    "Bengali Kheer",
    "Casino Ice Cream",
    "Icecream",
    "Amul Icecream",
    "Icecream with Brownie",
    "Rasgulla",
    "Spoongy Rasgulla",
    "RajBhog",
    "Garam Gulab Jamun",
    "Gulab Kheer",
    "Ghevar",
    "Shahi Tukda",
    "Bakery",
    "Paan",
    "Badam Katali",
    "Kaju Katli",
    "Fruit Cream",
  ],
  MainCourse: [
    "Dal Makhani",
    "Paneer Tikka Butter Masala",
    "Paneer Butter Masala",
    "Paneer Pasanda",
    "Paneer Lababdar",
    "Paneer Handi",
    "Nargis Kofta",
    "Shahi Korma",
    "Mutter Mushroom",
    "Choliya Mushroom",
    "Palak Chaap",
    "Palak Paneer",
    "Gravy Chaap",
    "Cheese Tomato",
    "Shahi Paneer",
    "Kadhai Paneer",
    "Amritsari Channa",
    "Dal Panchratan",
    "Dal Bukhara",
    "Daal Baati Choorma",
    "Palak Sweet Corn",
    "Navratn Korma",
    "Malai Kofta",
    "Malai Matar",
    "Palak Kofta",
    "Mushroom Kofta",
    "Keema Gobi",
    "Mix Veg",
    "Chana Masala",
    "Rajma Masala",
    "Tawa Paneer",
    "Navratn Tawa",
    "Baingan Bharta",
    "Bhindi Do Pyaza",
    "Aloo Gobi",
    "Methi Malai Mutter",
    "Yellow Dal",
    "Kadhi Pakoda",
    "Besan Gatte",
    "Dum Aloo",
    "Sarso Saag",
    "Pineapple Raita",
    "Veg Raita",
    "Plain Curd",
    "Boondi Raita",
    "Veg Biryani",
    "Jeera Rice",
    "Veg Pulav",
        "Salad",
    "SALAD Display",
    "Lehsun Chutney",
    "Imli Chutney",
    "Mint Sauce",
    "Vinegar Onion",
    "NON VEG",
    "Butter Chicken",
    "Chicken Tikka Masala",
    "Chicken Changezi",
    "Handi Chicken",
    "Mutton Laal Maas",
    "Mutton Rogan Josh",
    "Mutton Korma",
    "Mutton Karahi",
    "Fish Curry",
    "Tandoori Chicken",
    "Chicken Curry",
    "Chicken Biryani",

  ],
  Breads: [
    "Plain Roti",
    "Missi Roti",
    "Tava Roti",
    "Makki Di Roti",
    "Bajra Roti",
    "Butter Naan",
    "Lacha Parantha",
    "Garlic Naan",
  ],
};

export default categories;
