const categories = {
  HotCold: [
    "COFFEE Bar",
    "Soft Drinks (Pepsi, Sprite, Fanta)",
    "Cold Drinks Can",
    "Shake (Cold Coffee, Strawberry, Pista Butter Scotch)",
    "Mocktail Bar (Virgin Mohito, Blue Caraco, Passion Fruit)",
    "Coctail Bar",
    "Tomato Soup",
    "Manchow Soup",
    "Sweet Corn Soup",
    "Sweey & Sour Soup",
    "Water Bottle + Camper",
    "Water Bottle",
    "Water Camper"
  ],
    Breakfast: [
    "Paneer Pakoda",
    "Veg Cutlets",
    "Mix Pakoda",
    "Gobi Pakoda",
    "Cold Sandwich",
    "Grilled Sandwich",
    "Poha",
    "Aloo Paratha",
    "Omelette",
    "Chicken 65",
    "Fish Pakoda",
    "Lemon Chicken",
    "Egg Curry",
    "Tawa Mushroom",
    "Jullee",
    "Pastry",
    "Gulab Jamun",
    "Barfi",
    "Badaam Sandwich",
    "Kaju Katli",

    ],
  Stalls: [
    "Lacha Tikki",
    "Aaloo Tikki",
    "Raj Bhog Bhalle",
    "Dahi Bhalle",
    "Raj Kachori",
    "Palak Patta Chaat",
    "Gol Gappe",
    "Pav Bhaji",
    "Dosa",
    "SweetCorn",
    "Paneer Chilla",
    "Amritsari Naan Cholle",
    "Popcorn",
    "Fresh Fruit",
  ],
  Starters: [
    "French Fries",
    "Paneer Finger",
    "KFC Paneer",
    "Cheese Ball",
    "KFC Chaap",
    "Spring Roll",
    "Mushroom Duplex",
    "Hara Bhara Kebab",
    "Cocktail Kebab",
    "Italian Roll",
    "Veg Lolipop",
    "Fruit Kebab",
    "Cheese Stick",
    "Cheese Corn Roll",
    "Dahi Ke Cholle",
    "LIVE",
    "Manchurian",
    "Honey Chilli Paneer",
    "Honey Chilli Cauliflower",
    "Honey Chilli Potato",
    "Hakka Noodles",
    "Pasta (Red+White)",
    "Pepper Sweet Corn",
    "Cheese Nachos",
    "Steam Dimsum",
    "Italian Wrap",
    "Kathi Roll",
    "Cucumber Shot",
    "Tacos",
    "Maggie",
    "Canopy",
    "Dragon Paneer Chilli",
    "Paneer Tikka",
    "Achari Soyabean Tikka",
    "Malai Soyabean Tikka",
    "Masala Soyabean Tikka",
    "Hariyali Paneer Tikka",
    "Pizza",
    "NON VEG",
    // NON VEG
    "Chicken Tikka",
    "Chicken Tandoori",
    "Fish Tandoori",
    "Chicken Tangri",
    "Stuffed Tangri Kebab",
    "Dragon Chilli",
    "Chicken 65",
    "Tawa Mutton",
    "Handi Chicken",
    "Chicken Chili (Boneless)",
    "Pomfret Fish",
    "Tawa Red Sniper",
    "Lemon Fish",
    "Fish Pakoda",
    "Tawa Chicken",
    "Afghani Chicken",
  

  ],
  Sweets: [
    "Moong Dal Halwa",
    "GondPak",
    "Gajar Halwa",
    "Jalebi Rabdi",
    "Faluda Rabdi",
    "Casino Ice Cream",
    "Icecream",
    "Amul Icecream",
    "Rasgulla",
    "RajBhog",
    "Garam Gulab Jamun",
    "Gulab Kheer",
    "Ghevar",
    "Bakery",
  ],
  MainCourse: [
    "Dal Makhani",
    "Paneer Tikka Butter Masala",
    "Paneer Butter Masala",
    "Shahi Korma",
    "Mutter Mushroom",
    "Palak Chaap",
    "Gravy Chaap",
    "Cheese Tomato",
    "Shahi Paneer",
    "Kadhai Paneer",
    "Dal Panchratan",
    "Navratn Korma",
    "Malai Kofta",
    "Keema Gobi",
    "ChanaMasala",
    "Rajma Masala",
    "Tawa Paneer",
    "Navratn Tawa",
    "Baingan Bharta",
    "Bhindi Do Pyaza",
    "Aloo Gobi",
    "Methi Malai Mutter",
    "Yellow Dal",
    "Kadhi Pakoda",
    "Besan Gatte",
    "Dum Aloo",
    "Pineapple Raita",
    "Veg Raita",
    "Plain Curd",
    "Veg Biryani",
    "Jeera Rice",
    "NON VEG",
    "Butter Chicken",
    "Chicken Tikka Masala",
    "Chicken Changezi",
    "Handi Chicken",
    "Mutton Laal Maas",
    "Mutton Rogan Josh",
    "Mutton Korma",
    "Fish Curry",
    "Tandoori Chicken",
    "Chicken Curry",
    "Chicken Biryani",
    "Salad",
    "SALAD Display",
    "Lehsun Chutney",
  ],
  Breads: [
    "Plain Roti",
    "Missi Roti",
    "Butter Naan",
    "Lacha Parantha",
    "Garlic Naan",
  ],
};

export default categories;
